apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: failfast-ci-worker
  name: failfast-ci-worker
  selfLink: /apis/extensions/v1beta1/namespaces/hooktest/deployments/failfast-ci-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: failfast-ci-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: failfast-ci-worker
    spec:
      containers:
      - command:
        - celery
        - -A
        - hub2labhook.jobs.runner
        - worker
        - -l
        - debug
        volumeMounts:
          - name: failfast-config
            mountPath: /etc/failfast-ci
        env:
        - name: CELERY_BACKEND
          value: redis://failfast-redis.hooktest.svc.cluster.local:6379
        - name: CELERY_BROKER
          value: redis://failfast-redis.hooktest.svc.cluster.local:6379
        - name: GITHUB_INTEGRATION_PEM
          valueFrom:
            secretKeyRef:
              key: integration_pem
              name: failfast-ci
        - name: FFCI_CONF_FILE
          value: /etc/failfast-ci/failfast-ci.yaml
        image: quay.io/failfast-ci/failfast-cibuild:pr-36-failfast-configuration-8b7ba189
        imagePullPolicy: Always
        name: failfast-ci-worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: failfast-config
          configMap:
            name: failfast-ci
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
