apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kpm.hash: 5eae3659be72df127e7655d986df5b91054f715476c7c56fb34cd10bd06071fe
    kpm.package: ant31/hub2lab-hook
    kpm.parent: ant31/hub2lab-hook
    kpm.protected: "false"
    kpm.version: 0.0.2-2
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4","kpm.hash":"5eae3659be72df127e7655d986df5b91054f715476c7c56fb34cd10bd06071fe","kpm.package":"ant31/hub2lab-hook","kpm.parent":"ant31/hub2lab-hook","kpm.protected":"false","kpm.version":"0.0.2-2"},"creationTimestamp":"2016-12-09T20:30:15Z","generation":3,"labels":{"k8s-app":"redis"},"name":"redis","namespace":"hooktest","resourceVersion":"82613213","selfLink":"/apis/extensions/v1beta1/namespaces/hooktest/deployments/redis","uid":"4aa44fcd-be4e-11e6-af39-0007cb03fac4"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"redis"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-app":"redis"}},"spec":{"containers":[{"image":"redis:3","imagePullPolicy":"IfNotPresent","name":"redis","ports":[{"containerPort":6379,"name":"redis","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data","name":"data"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{"sizeLimit":"0"},"name":"data"}]}}},"status":{"conditions":[{"lastTransitionTime":"2016-12-17T19:13:53Z","lastUpdateTime":"2016-12-17T19:13:53Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":3,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: failfast-redis
  name: redis
  selfLink: /apis/extensions/v1beta1/namespaces/hooktest/deployments/redis
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: failfast-redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: failfast-redis
    spec:
      containers:
      - image: redis:3
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
status: {}
