---
kind: Manifest
apiVersion: manifest.k8s.io/v1alpha1
metadata:
  creationTimestamp: null
  name: failfast-ci

objectLabels:
  app.kubernetes.io/name: failfast-ci
  app.kubernetes.io/version: v0.4.0

configmaps:
- files:
  - configmaps/failfast-ci.yaml
  name: failfast-ci

genericSecrets:
- files:
  - secrets/integration_pem
  name: failfast-ci

resources:
- resources/failfast-ci.ingress.yaml

packages:
- ../base-package
